/* RobotDataClient.cpp
   Generated by gSOAP 2.8.16 from .\robotdata.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "RobotDataH.h"

namespace RobotData {

SOAP_SOURCE_STAMP("@(#) RobotDataClient.cpp ver 2.8.16 2020-03-04 05:49:42 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRobotConnect(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRobotConnect *ns3__GetRobotConnect, _ns3__GetRobotConnectResponse *ns3__GetRobotConnectResponse)
{	struct __ns1__GetRobotConnect soap_tmp___ns1__GetRobotConnect;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRobotConnect.ns3__GetRobotConnect = ns3__GetRobotConnect;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRobotConnect(soap, &soap_tmp___ns1__GetRobotConnect);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRobotConnect(soap, &soap_tmp___ns1__GetRobotConnect, "-ns1:GetRobotConnect", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRobotConnect(soap, &soap_tmp___ns1__GetRobotConnect, "-ns1:GetRobotConnect", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRobotConnectResponse)
		return soap_closesock(soap);
	ns3__GetRobotConnectResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRobotConnectResponse->soap_get(soap, "ns3:GetRobotConnectResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRobotInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRobotInfo *ns3__GetRobotInfo, _ns3__GetRobotInfoResponse *ns3__GetRobotInfoResponse)
{	struct __ns1__GetRobotInfo soap_tmp___ns1__GetRobotInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRobotInfo.ns3__GetRobotInfo = ns3__GetRobotInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRobotInfo(soap, &soap_tmp___ns1__GetRobotInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRobotInfo(soap, &soap_tmp___ns1__GetRobotInfo, "-ns1:GetRobotInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRobotInfo(soap, &soap_tmp___ns1__GetRobotInfo, "-ns1:GetRobotInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRobotInfoResponse)
		return soap_closesock(soap);
	ns3__GetRobotInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRobotInfoResponse->soap_get(soap, "ns3:GetRobotInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRobotTime(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRobotTime *ns3__GetRobotTime, _ns3__GetRobotTimeResponse *ns3__GetRobotTimeResponse)
{	struct __ns1__GetRobotTime soap_tmp___ns1__GetRobotTime;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRobotTime.ns3__GetRobotTime = ns3__GetRobotTime;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRobotTime(soap, &soap_tmp___ns1__GetRobotTime);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRobotTime(soap, &soap_tmp___ns1__GetRobotTime, "-ns1:GetRobotTime", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRobotTime(soap, &soap_tmp___ns1__GetRobotTime, "-ns1:GetRobotTime", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRobotTimeResponse)
		return soap_closesock(soap);
	ns3__GetRobotTimeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRobotTimeResponse->soap_get(soap, "ns3:GetRobotTimeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetRobotTime(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__SetRobotTime *ns3__SetRobotTime, _ns3__SetRobotTimeResponse *ns3__SetRobotTimeResponse)
{	struct __ns1__SetRobotTime soap_tmp___ns1__SetRobotTime;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetRobotTime.ns3__SetRobotTime = ns3__SetRobotTime;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetRobotTime(soap, &soap_tmp___ns1__SetRobotTime);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetRobotTime(soap, &soap_tmp___ns1__SetRobotTime, "-ns1:SetRobotTime", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetRobotTime(soap, &soap_tmp___ns1__SetRobotTime, "-ns1:SetRobotTime", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__SetRobotTimeResponse)
		return soap_closesock(soap);
	ns3__SetRobotTimeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__SetRobotTimeResponse->soap_get(soap, "ns3:SetRobotTimeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetCurrentRobot(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__SetCurrentRobot *ns3__SetCurrentRobot, _ns3__SetCurrentRobotResponse *ns3__SetCurrentRobotResponse)
{	struct __ns1__SetCurrentRobot soap_tmp___ns1__SetCurrentRobot;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetCurrentRobot.ns3__SetCurrentRobot = ns3__SetCurrentRobot;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetCurrentRobot(soap, &soap_tmp___ns1__SetCurrentRobot);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetCurrentRobot(soap, &soap_tmp___ns1__SetCurrentRobot, "-ns1:SetCurrentRobot", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetCurrentRobot(soap, &soap_tmp___ns1__SetCurrentRobot, "-ns1:SetCurrentRobot", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__SetCurrentRobotResponse)
		return soap_closesock(soap);
	ns3__SetCurrentRobotResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__SetCurrentRobotResponse->soap_get(soap, "ns3:SetCurrentRobotResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ReleaseCurrentRobot(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__ReleaseCurrentRobot *ns3__ReleaseCurrentRobot, _ns3__ReleaseCurrentRobotResponse *ns3__ReleaseCurrentRobotResponse)
{	struct __ns1__ReleaseCurrentRobot soap_tmp___ns1__ReleaseCurrentRobot;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__ReleaseCurrentRobot.ns3__ReleaseCurrentRobot = ns3__ReleaseCurrentRobot;
	soap_serializeheader(soap);
	soap_serialize___ns1__ReleaseCurrentRobot(soap, &soap_tmp___ns1__ReleaseCurrentRobot);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ReleaseCurrentRobot(soap, &soap_tmp___ns1__ReleaseCurrentRobot, "-ns1:ReleaseCurrentRobot", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ReleaseCurrentRobot(soap, &soap_tmp___ns1__ReleaseCurrentRobot, "-ns1:ReleaseCurrentRobot", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__ReleaseCurrentRobotResponse)
		return soap_closesock(soap);
	ns3__ReleaseCurrentRobotResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__ReleaseCurrentRobotResponse->soap_get(soap, "ns3:ReleaseCurrentRobotResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__SetControlMode(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__SetControlMode *ns3__SetControlMode, _ns3__SetControlModeResponse *ns3__SetControlModeResponse)
{	struct __ns1__SetControlMode soap_tmp___ns1__SetControlMode;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__SetControlMode.ns3__SetControlMode = ns3__SetControlMode;
	soap_serializeheader(soap);
	soap_serialize___ns1__SetControlMode(soap, &soap_tmp___ns1__SetControlMode);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__SetControlMode(soap, &soap_tmp___ns1__SetControlMode, "-ns1:SetControlMode", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__SetControlMode(soap, &soap_tmp___ns1__SetControlMode, "-ns1:SetControlMode", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__SetControlModeResponse)
		return soap_closesock(soap);
	ns3__SetControlModeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__SetControlModeResponse->soap_get(soap, "ns3:SetControlModeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetControlMode(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetControlMode *ns3__GetControlMode, _ns3__GetControlModeResponse *ns3__GetControlModeResponse)
{	struct __ns1__GetControlMode soap_tmp___ns1__GetControlMode;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetControlMode.ns3__GetControlMode = ns3__GetControlMode;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetControlMode(soap, &soap_tmp___ns1__GetControlMode);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetControlMode(soap, &soap_tmp___ns1__GetControlMode, "-ns1:GetControlMode", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetControlMode(soap, &soap_tmp___ns1__GetControlMode, "-ns1:GetControlMode", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetControlModeResponse)
		return soap_closesock(soap);
	ns3__GetControlModeResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetControlModeResponse->soap_get(soap, "ns3:GetControlModeResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RobotSpeedControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__RobotSpeedControl *ns3__RobotSpeedControl, _ns3__RobotSpeedControlResponse *ns3__RobotSpeedControlResponse)
{	struct __ns1__RobotSpeedControl soap_tmp___ns1__RobotSpeedControl;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__RobotSpeedControl.ns3__RobotSpeedControl = ns3__RobotSpeedControl;
	soap_serializeheader(soap);
	soap_serialize___ns1__RobotSpeedControl(soap, &soap_tmp___ns1__RobotSpeedControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RobotSpeedControl(soap, &soap_tmp___ns1__RobotSpeedControl, "-ns1:RobotSpeedControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RobotSpeedControl(soap, &soap_tmp___ns1__RobotSpeedControl, "-ns1:RobotSpeedControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__RobotSpeedControlResponse)
		return soap_closesock(soap);
	ns3__RobotSpeedControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__RobotSpeedControlResponse->soap_get(soap, "ns3:RobotSpeedControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RobotYuntaiControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__RobotYuntaiControl *ns3__RobotYuntaiControl, _ns3__RobotYuntaiControlResponse *ns3__RobotYuntaiControlResponse)
{	struct __ns1__RobotYuntaiControl soap_tmp___ns1__RobotYuntaiControl;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__RobotYuntaiControl.ns3__RobotYuntaiControl = ns3__RobotYuntaiControl;
	soap_serializeheader(soap);
	soap_serialize___ns1__RobotYuntaiControl(soap, &soap_tmp___ns1__RobotYuntaiControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RobotYuntaiControl(soap, &soap_tmp___ns1__RobotYuntaiControl, "-ns1:RobotYuntaiControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RobotYuntaiControl(soap, &soap_tmp___ns1__RobotYuntaiControl, "-ns1:RobotYuntaiControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__RobotYuntaiControlResponse)
		return soap_closesock(soap);
	ns3__RobotYuntaiControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__RobotYuntaiControlResponse->soap_get(soap, "ns3:RobotYuntaiControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RobotCameraControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__RobotCameraControl *ns3__RobotCameraControl, _ns3__RobotCameraControlResponse *ns3__RobotCameraControlResponse)
{	struct __ns1__RobotCameraControl soap_tmp___ns1__RobotCameraControl;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__RobotCameraControl.ns3__RobotCameraControl = ns3__RobotCameraControl;
	soap_serializeheader(soap);
	soap_serialize___ns1__RobotCameraControl(soap, &soap_tmp___ns1__RobotCameraControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RobotCameraControl(soap, &soap_tmp___ns1__RobotCameraControl, "-ns1:RobotCameraControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RobotCameraControl(soap, &soap_tmp___ns1__RobotCameraControl, "-ns1:RobotCameraControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__RobotCameraControlResponse)
		return soap_closesock(soap);
	ns3__RobotCameraControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__RobotCameraControlResponse->soap_get(soap, "ns3:RobotCameraControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RobotLightControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__RobotLightControl *ns3__RobotLightControl, _ns3__RobotLightControlResponse *ns3__RobotLightControlResponse)
{	struct __ns1__RobotLightControl soap_tmp___ns1__RobotLightControl;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__RobotLightControl.ns3__RobotLightControl = ns3__RobotLightControl;
	soap_serializeheader(soap);
	soap_serialize___ns1__RobotLightControl(soap, &soap_tmp___ns1__RobotLightControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RobotLightControl(soap, &soap_tmp___ns1__RobotLightControl, "-ns1:RobotLightControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RobotLightControl(soap, &soap_tmp___ns1__RobotLightControl, "-ns1:RobotLightControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__RobotLightControlResponse)
		return soap_closesock(soap);
	ns3__RobotLightControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__RobotLightControlResponse->soap_get(soap, "ns3:RobotLightControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RobotWiperControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__RobotWiperControl *ns3__RobotWiperControl, _ns3__RobotWiperControlResponse *ns3__RobotWiperControlResponse)
{	struct __ns1__RobotWiperControl soap_tmp___ns1__RobotWiperControl;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__RobotWiperControl.ns3__RobotWiperControl = ns3__RobotWiperControl;
	soap_serializeheader(soap);
	soap_serialize___ns1__RobotWiperControl(soap, &soap_tmp___ns1__RobotWiperControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RobotWiperControl(soap, &soap_tmp___ns1__RobotWiperControl, "-ns1:RobotWiperControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RobotWiperControl(soap, &soap_tmp___ns1__RobotWiperControl, "-ns1:RobotWiperControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__RobotWiperControlResponse)
		return soap_closesock(soap);
	ns3__RobotWiperControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__RobotWiperControlResponse->soap_get(soap, "ns3:RobotWiperControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RobotFlirControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__RobotFlirControl *ns3__RobotFlirControl, _ns3__RobotFlirControlResponse *ns3__RobotFlirControlResponse)
{	struct __ns1__RobotFlirControl soap_tmp___ns1__RobotFlirControl;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__RobotFlirControl.ns3__RobotFlirControl = ns3__RobotFlirControl;
	soap_serializeheader(soap);
	soap_serialize___ns1__RobotFlirControl(soap, &soap_tmp___ns1__RobotFlirControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RobotFlirControl(soap, &soap_tmp___ns1__RobotFlirControl, "-ns1:RobotFlirControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RobotFlirControl(soap, &soap_tmp___ns1__RobotFlirControl, "-ns1:RobotFlirControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__RobotFlirControlResponse)
		return soap_closesock(soap);
	ns3__RobotFlirControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__RobotFlirControlResponse->soap_get(soap, "ns3:RobotFlirControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RobotLifterControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__RobotLifterControl *ns3__RobotLifterControl, _ns3__RobotLifterControlResponse *ns3__RobotLifterControlResponse)
{	struct __ns1__RobotLifterControl soap_tmp___ns1__RobotLifterControl;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__RobotLifterControl.ns3__RobotLifterControl = ns3__RobotLifterControl;
	soap_serializeheader(soap);
	soap_serialize___ns1__RobotLifterControl(soap, &soap_tmp___ns1__RobotLifterControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RobotLifterControl(soap, &soap_tmp___ns1__RobotLifterControl, "-ns1:RobotLifterControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RobotLifterControl(soap, &soap_tmp___ns1__RobotLifterControl, "-ns1:RobotLifterControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__RobotLifterControlResponse)
		return soap_closesock(soap);
	ns3__RobotLifterControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__RobotLifterControlResponse->soap_get(soap, "ns3:RobotLifterControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__RobotPdControl(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__RobotPdControl *ns3__RobotPdControl, _ns3__RobotPdControlResponse *ns3__RobotPdControlResponse)
{	struct __ns1__RobotPdControl soap_tmp___ns1__RobotPdControl;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__RobotPdControl.ns3__RobotPdControl = ns3__RobotPdControl;
	soap_serializeheader(soap);
	soap_serialize___ns1__RobotPdControl(soap, &soap_tmp___ns1__RobotPdControl);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__RobotPdControl(soap, &soap_tmp___ns1__RobotPdControl, "-ns1:RobotPdControl", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__RobotPdControl(soap, &soap_tmp___ns1__RobotPdControl, "-ns1:RobotPdControl", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__RobotPdControlResponse)
		return soap_closesock(soap);
	ns3__RobotPdControlResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__RobotPdControlResponse->soap_get(soap, "ns3:RobotPdControlResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRobotBatteryInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRobotBatteryInfo *ns3__GetRobotBatteryInfo, _ns3__GetRobotBatteryInfoResponse *ns3__GetRobotBatteryInfoResponse)
{	struct __ns1__GetRobotBatteryInfo soap_tmp___ns1__GetRobotBatteryInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRobotBatteryInfo.ns3__GetRobotBatteryInfo = ns3__GetRobotBatteryInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRobotBatteryInfo(soap, &soap_tmp___ns1__GetRobotBatteryInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRobotBatteryInfo(soap, &soap_tmp___ns1__GetRobotBatteryInfo, "-ns1:GetRobotBatteryInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRobotBatteryInfo(soap, &soap_tmp___ns1__GetRobotBatteryInfo, "-ns1:GetRobotBatteryInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRobotBatteryInfoResponse)
		return soap_closesock(soap);
	ns3__GetRobotBatteryInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRobotBatteryInfoResponse->soap_get(soap, "ns3:GetRobotBatteryInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRobotSpeedInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRobotSpeedInfo *ns3__GetRobotSpeedInfo, _ns3__GetRobotSpeedInfoResponse *ns3__GetRobotSpeedInfoResponse)
{	struct __ns1__GetRobotSpeedInfo soap_tmp___ns1__GetRobotSpeedInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRobotSpeedInfo.ns3__GetRobotSpeedInfo = ns3__GetRobotSpeedInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRobotSpeedInfo(soap, &soap_tmp___ns1__GetRobotSpeedInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRobotSpeedInfo(soap, &soap_tmp___ns1__GetRobotSpeedInfo, "-ns1:GetRobotSpeedInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRobotSpeedInfo(soap, &soap_tmp___ns1__GetRobotSpeedInfo, "-ns1:GetRobotSpeedInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRobotSpeedInfoResponse)
		return soap_closesock(soap);
	ns3__GetRobotSpeedInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRobotSpeedInfoResponse->soap_get(soap, "ns3:GetRobotSpeedInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRobotTaskState(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRobotTaskState *ns3__GetRobotTaskState, _ns3__GetRobotTaskStateResponse *ns3__GetRobotTaskStateResponse)
{	struct __ns1__GetRobotTaskState soap_tmp___ns1__GetRobotTaskState;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRobotTaskState.ns3__GetRobotTaskState = ns3__GetRobotTaskState;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRobotTaskState(soap, &soap_tmp___ns1__GetRobotTaskState);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRobotTaskState(soap, &soap_tmp___ns1__GetRobotTaskState, "-ns1:GetRobotTaskState", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRobotTaskState(soap, &soap_tmp___ns1__GetRobotTaskState, "-ns1:GetRobotTaskState", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRobotTaskStateResponse)
		return soap_closesock(soap);
	ns3__GetRobotTaskStateResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRobotTaskStateResponse->soap_get(soap, "ns3:GetRobotTaskStateResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRobotPosInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRobotPosInfo *ns3__GetRobotPosInfo, _ns3__GetRobotPosInfoResponse *ns3__GetRobotPosInfoResponse)
{	struct __ns1__GetRobotPosInfo soap_tmp___ns1__GetRobotPosInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRobotPosInfo.ns3__GetRobotPosInfo = ns3__GetRobotPosInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRobotPosInfo(soap, &soap_tmp___ns1__GetRobotPosInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRobotPosInfo(soap, &soap_tmp___ns1__GetRobotPosInfo, "-ns1:GetRobotPosInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRobotPosInfo(soap, &soap_tmp___ns1__GetRobotPosInfo, "-ns1:GetRobotPosInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRobotPosInfoResponse)
		return soap_closesock(soap);
	ns3__GetRobotPosInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRobotPosInfoResponse->soap_get(soap, "ns3:GetRobotPosInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRobotYunTaiInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRobotYunTaiInfo *ns3__GetRobotYunTaiInfo, _ns3__GetRobotYunTaiInfoResponse *ns3__GetRobotYunTaiInfoResponse)
{	struct __ns1__GetRobotYunTaiInfo soap_tmp___ns1__GetRobotYunTaiInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRobotYunTaiInfo.ns3__GetRobotYunTaiInfo = ns3__GetRobotYunTaiInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRobotYunTaiInfo(soap, &soap_tmp___ns1__GetRobotYunTaiInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRobotYunTaiInfo(soap, &soap_tmp___ns1__GetRobotYunTaiInfo, "-ns1:GetRobotYunTaiInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRobotYunTaiInfo(soap, &soap_tmp___ns1__GetRobotYunTaiInfo, "-ns1:GetRobotYunTaiInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRobotYunTaiInfoResponse)
		return soap_closesock(soap);
	ns3__GetRobotYunTaiInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRobotYunTaiInfoResponse->soap_get(soap, "ns3:GetRobotYunTaiInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRobotMileageInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRobotMileageInfo *ns3__GetRobotMileageInfo, _ns3__GetRobotMileageInfoResponse *ns3__GetRobotMileageInfoResponse)
{	struct __ns1__GetRobotMileageInfo soap_tmp___ns1__GetRobotMileageInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRobotMileageInfo.ns3__GetRobotMileageInfo = ns3__GetRobotMileageInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRobotMileageInfo(soap, &soap_tmp___ns1__GetRobotMileageInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRobotMileageInfo(soap, &soap_tmp___ns1__GetRobotMileageInfo, "-ns1:GetRobotMileageInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRobotMileageInfo(soap, &soap_tmp___ns1__GetRobotMileageInfo, "-ns1:GetRobotMileageInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRobotMileageInfoResponse)
		return soap_closesock(soap);
	ns3__GetRobotMileageInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRobotMileageInfoResponse->soap_get(soap, "ns3:GetRobotMileageInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRobotGasInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRobotGasInfo *ns3__GetRobotGasInfo, _ns3__GetRobotGasInfoResponse *ns3__GetRobotGasInfoResponse)
{	struct __ns1__GetRobotGasInfo soap_tmp___ns1__GetRobotGasInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRobotGasInfo.ns3__GetRobotGasInfo = ns3__GetRobotGasInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRobotGasInfo(soap, &soap_tmp___ns1__GetRobotGasInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRobotGasInfo(soap, &soap_tmp___ns1__GetRobotGasInfo, "-ns1:GetRobotGasInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRobotGasInfo(soap, &soap_tmp___ns1__GetRobotGasInfo, "-ns1:GetRobotGasInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRobotGasInfoResponse)
		return soap_closesock(soap);
	ns3__GetRobotGasInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRobotGasInfoResponse->soap_get(soap, "ns3:GetRobotGasInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__GetRobotAlarmInfo(struct soap *soap, const char *soap_endpoint, const char *soap_action, _ns3__GetRobotAlarmInfo *ns3__GetRobotAlarmInfo, _ns3__GetRobotAlarmInfoResponse *ns3__GetRobotAlarmInfoResponse)
{	struct __ns1__GetRobotAlarmInfo soap_tmp___ns1__GetRobotAlarmInfo;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:80";
	if (soap_action == NULL)
		soap_action = "";
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_tmp___ns1__GetRobotAlarmInfo.ns3__GetRobotAlarmInfo = ns3__GetRobotAlarmInfo;
	soap_serializeheader(soap);
	soap_serialize___ns1__GetRobotAlarmInfo(soap, &soap_tmp___ns1__GetRobotAlarmInfo);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__GetRobotAlarmInfo(soap, &soap_tmp___ns1__GetRobotAlarmInfo, "-ns1:GetRobotAlarmInfo", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__GetRobotAlarmInfo(soap, &soap_tmp___ns1__GetRobotAlarmInfo, "-ns1:GetRobotAlarmInfo", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!ns3__GetRobotAlarmInfoResponse)
		return soap_closesock(soap);
	ns3__GetRobotAlarmInfoResponse->soap_default(soap);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	ns3__GetRobotAlarmInfoResponse->soap_get(soap, "ns3:GetRobotAlarmInfoResponse", "");
	if (soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

} // namespace RobotData


#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of RobotDataClient.cpp */
